# Generated by Django 4.2.29 on 2026-03-16 19:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('faculty', models.CharField(choices=[('business', 'Business'), ('agriculture', 'Agriculture'), ('computing', 'Computing & IT'), ('education', 'Education'), ('science', 'Science'), ('engineering', 'Engineering')], max_length=50)),
                ('description', models.TextField()),
                ('duration_years', models.PositiveIntegerField(default=4)),
                ('minimum_grade', models.CharField(help_text='Minimum KCSE grade e.g. C+', max_length=5)),
                ('minimum_points', models.PositiveIntegerField(help_text='Minimum KCSE points (out of 84)')),
                ('required_subjects', models.TextField(help_text='Comma-separated list of required subjects')),
                ('skills_developed', models.TextField(help_text='Comma-separated list of skills')),
                ('career_paths', models.TextField(help_text='Comma-separated possible careers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['faculty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('office_location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('enrollment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='dss_guidance.academicprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('business_finance', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('healthcare', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('education_teaching', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('agriculture_environment', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('engineering', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('research_science', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('arts_communication', models.IntegerField(choices=[(1, 'Not Interested'), (2, 'Slightly Interested'), (3, 'Moderately Interested'), (4, 'Interested'), (5, 'Very Interested')], default=3)),
                ('prefers_fieldwork', models.BooleanField(default=False)),
                ('prefers_research', models.BooleanField(default=False)),
                ('prefers_people_interaction', models.BooleanField(default=False)),
                ('prefers_technical_work', models.BooleanField(default=False)),
                ('career_goal', models.TextField(blank=True, help_text='Describe your career goal')),
                ('preferred_work_location', models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural'), ('both', 'Both')], default='both', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='dss_guidance.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reasoning', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed by Advisor'), ('accepted', 'Accepted by Student'), ('declined', 'Declined by Student')], default='pending', max_length=20)),
                ('advisor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='dss_guidance.academicprogram')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='dss_guidance.studentprofile')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='KCSEResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=20, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('overall_grade', models.CharField(choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('total_points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(84)])),
                ('mathematics', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('english', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('kiswahili', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('biology', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('chemistry', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('physics', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('history', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('geography', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('business_studies', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('agriculture', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('computer_studies', models.CharField(blank=True, choices=[('A', 'A (81–84)'), ('A-', 'A- (74–80)'), ('B+', 'B+ (67–73)'), ('B', 'B (60–66)'), ('B-', 'B- (53–59)'), ('C+', 'C+ (46–52)'), ('C', 'C (40–45)'), ('C-', 'C- (33–39)'), ('D+', 'D+ (26–32)'), ('D', 'D (20–25)'), ('D-', 'D- (13–19)'), ('E', 'E (00–12)')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kcse_result', to='dss_guidance.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dss_guidance.advisorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dss_guidance.studentprofile')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='advisorprofile',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='advisors', to='dss_guidance.studentprofile'),
        ),
        migrations.AddField(
            model_name='advisorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UniversityPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20)),
                ('unit_name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('grade', models.CharField(choices=[('A', 'A (70–100%)'), ('B+', 'B+ (65–69%)'), ('B', 'B (60–64%)'), ('C+', 'C+ (55–59%)'), ('C', 'C (50–54%)'), ('D+', 'D+ (45–49%)'), ('D', 'D (40–44%)'), ('E', 'E (Below 40%)')], max_length=3)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_performance', to='dss_guidance.studentprofile')),
            ],
            options={
                'ordering': ['year', 'semester'],
                'unique_together': {('student', 'unit_code', 'year', 'semester')},
            },
        ),
    ]
